(ns thefinalcountapp.data.schemas
       
                                
        
  (:require [schema.core :as s :include-macros true]))


(def NewGroup
  {:name s/Str})


(def NewCounter
  {:type (s/enum :count-up
                 :streak
                 :counter)
   :text s/Str
   :color (s/enum :red
                  :pink
                  :blue
                  :purple
                  :yellow)
  (s/optional-key :value) s/Int
  (s/optional-key :public-reset) s/Bool
  (s/optional-key :public-plus) s/Bool})


(def CounterUpdate
  {(s/optional-key :text) s/Str
   (s/optional-key :value) s/Int
   (s/optional-key :public-reset) s/Bool
   (s/optional-key :public-plus) s/Bool})

;;;;;;;;;;;; This file autogenerated from src/cljx/thefinalcountapp/data/schemas.cljx
